## 步骤一：获取中证800分类数据（市值特点）
需要获取的板块：[HS300, ZZ500]

HS300（沪深300）反映的是流动性强和规模大的300只代表性股票的股价的综合变动。

ZZ500（中证500）全部A股中剔除沪深300指数成份股及总市值排名前300名的股票后，总市值排名靠前的500只股票组成。

In [1]:
from jaqs_fxdayu.util import dp
from jaqs.data.dataapi import DataApi



api = DataApi(addr='tcp://data.tushare.org:8910')
api.login("18838961432", 
          'eyJhbGciOiJIUzI1NiJ9.eyJjcmVhdGVfdGltZSI6IjE1MjIwNjA1NDA0MTAiLCJpc3MiOiJhdXRoMCIsImlkIjoiMTg4Mzg5NjE0MzIifQ.itvE1WWBn_AYmbbNGQX2CsKgIq3Tmdt5tD-QtaQWyJo'
)

start = 20130101
end = 20180101
SH_id = dp.index_cons(api, "000300.SH", start, end)
SZ_id = dp.index_cons(api, "000905.SH", start, end)

stock_symbol = list(set(SH_id.symbol)|set(SZ_id.symbol))

## 步骤二：读取数据
数据下载到本地的data

In [2]:
factor_list = ['close_adj','volume','high','low']
check_factor = ','.join(factor_list)

In [3]:
import jaqs_fxdayu
jaqs_fxdayu.patch_all()
from jaqs.data import DataView
from jaqs.data import RemoteDataService
from jaqs_fxdayu.data.dataservice import LocalDataService
import os
import numpy as np
import warnings
warnings.filterwarnings("ignore")

dataview_folder = 'C:/data'
dv = DataView()
ds = LocalDataService(fp=dataview_folder)

dv_props = {'start_date': start, 'end_date': end, 'symbol':','.join(stock_symbol),
         'fields': check_factor,
         'freq': 1,
         "prepare_fields": True}

dv.init_from_config(dv_props, data_api=ds)
dv.prepare_data()

D:\Software\Anaconda3_64\envs\fxdayu\lib\importlib\__init__.py:126: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  return _bootstrap._gcd_import(name[level:], package, level)
D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\jaqs\research\signaldigger\plotting.py:10: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-12d720efe20f>", line 1, in <module>
    from jaqs_fxdayu.util import dp
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\jaqs_fxdayu\__init__.py", line 4, in <module>
    import matplotlib.pyplot  # 防止被JAQS重载
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\matplotlib\pyplot.py", line 69, in <module>
    from matplotlib.backends import pylab_setup
  File "D:\Software\Anaconda3_64\envs\fxdayu\lib\site-packages\matplotlib\backends\__init__.py", line 14, in <module>
    line for line in traceback.format_stack()


  mpl.use('Agg')

Initialize config success.
Query data...
Query data - query...
NOTE: price adjust method is [post adjust]
当前请求daily...
{'adjust_mode': None, 'fields': 'volume,close,high_adj,low_adj,vwap_adj,trade_status,high,low,open_adj,close_adj,open,trade_date,vwap,symbol'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
当前请求daily...
{'adjust_mode': 'post', 'fields': 'close,high,low,open,vwap,symbol,trade_date'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - daily fields prepared.
Query instrument info...
Query adj_factor...
Data has been successfully prepared.

## Spearman_Check

In [4]:
import scipy.stats as scst
import jaqs.util as jutill


def spearman_factor(factor_u='factor_u', factor_j='factor_j', start=20160101, symbol=stock_symbol):
    factors = dict()
    factors["factor_u"] = dv.get_ts(factor_u).loc[start:][stock_symbol].stack()
    factors["factor_j"] = dv.get_ts(factor_j).loc[start:][stock_symbol].stack()

    factors_df = pd.concat(factors.values(),axis=1)
    factors_df.columns = factors.keys()
    factors_df = jutill.fillinf(factors_df).dropna()

    # 两个因子的spearman相关性
    def get_factors_daily_corr(factors_df,
                               f1="factor_u",
                               f2="factor_j"):
        def _cal_corr(df):
            return scst.spearmanr(df[f1], df[f2])[0]

        result = factors_df.groupby(['trade_date']).apply(_cal_corr)
        result = pd.DataFrame(result)
        result.columns = ['spearmanr']
        return result

    result = get_factors_daily_corr(factors_df,"factor_u","factor_j")
    t_stat, p_value = scst.ttest_1samp(result, 0)
    return result.mean(), p_value # 相关关系均值,相关关系均值的ｔ统计量的p_value

## 步骤三：获取分类数据

可获取的分类：[sw1, sw2, sw3, zz1, zz2]

sw1 =  {'480000': '银行', '430000': '房地产', '460000': '休闲服务', '640000': '机械设备', '240000': '有色金属', '510000': '综合', '410000': '公用事业', '450000': '商业贸易', '730000': '通信', '330000': '家用电器', '720000': '传媒', '630000': '电气设备', '270000': '电子', '490000': '非银金融', '370000': '医药生物', '710000': '计算机', '280000': '汽车', '340000': '食品饮料', '220000': '化工', '210000': '采掘', '230000': '钢铁', '650000': '国防军工', '110000': '农林牧渔', '420000': '交通运输', '620000': '建筑装饰', '350000': '纺织服装', '610000': '建筑材料', '360000': '轻工制造'}

In [5]:
dv.add_field('sw1')

True

In [6]:
sw1 = dv.get_ts('sw1')

In [7]:
dict_classify = {'480000': '银行', '430000': '房地产', '460000': '休闲服务', '640000': '机械设备', '240000': '有色金属', '510000': '综合', '410000': '公用事业', '450000': '商业贸易', '730000': '通信', '330000': '家用电器', '720000': '传媒', '630000': '电气设备', '270000': '电子', '490000': '非银金融', '370000': '医药生物', '710000': '计算机', '280000': '汽车', '340000': '食品饮料', '220000': '化工', '210000': '采掘', '230000': '钢铁', '650000': '国防军工', '110000': '农林牧渔', '420000': '交通运输', '620000': '建筑装饰', '350000': '纺织服装', '610000': '建筑材料', '360000': '轻工制造'}

In [8]:
sw1_name = sw1.replace(dict_classify)

In [9]:
sw1_name.tail()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20171225,银行,房地产,房地产,机械设备,综合,建筑材料,计算机,nan,汽车,公用事业,...,轻工制造,医药生物,食品饮料,家用电器,纺织服装,医药生物,交通运输,传媒,轻工制造,有色金属
20171226,银行,房地产,房地产,机械设备,综合,建筑材料,计算机,nan,汽车,公用事业,...,轻工制造,医药生物,食品饮料,家用电器,纺织服装,医药生物,交通运输,传媒,轻工制造,有色金属
20171227,银行,房地产,房地产,机械设备,综合,建筑材料,计算机,nan,汽车,公用事业,...,轻工制造,医药生物,食品饮料,家用电器,纺织服装,医药生物,交通运输,传媒,轻工制造,有色金属
20171228,银行,房地产,房地产,机械设备,综合,建筑材料,计算机,nan,汽车,公用事业,...,轻工制造,医药生物,食品饮料,家用电器,纺织服装,医药生物,交通运输,传媒,轻工制造,有色金属
20171229,银行,房地产,房地产,机械设备,综合,建筑材料,计算机,nan,汽车,公用事业,...,轻工制造,医药生物,食品饮料,家用电器,纺织服装,医药生物,交通运输,传媒,轻工制造,有色金属

## 步骤四： 输入已经写好的因子（数据或算法）
算法：add_formula()

数据：dv.get_ts()

### MassIndex

In [10]:
dv.add_field('MassIndex')

Query data - query...
当前请求query...
{'fields': 'MassIndex', 'view': 'factor'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - daily fields prepared.

True

In [11]:
MassIndex_U=dv.get_ts('MassIndex')

In [12]:
EMAHL=dv.add_formula("EMAHL","Ta('EMA',0,high_adj-low_adj,high_adj-low_adj,high_adj-low_adj,high_adj-low_adj,high_adj-close_adj,9)",is_quarterly=False,add_data=True)

In [13]:
EMA_Ratio_=dv.add_formula('EMA_Ratio_',"Ta('EMA',0,EMAHL,EMAHL,EMAHL,EMAHL,EMAHL,9)",is_quarterly=False,add_data=True)

In [14]:
EMA_Ratio=dv.add_formula('EMA_Ratio','EMAHL/EMA_Ratio_',is_quarterly=False,add_data=True)

In [15]:
MassIndex_J=dv.add_formula('MassIndex_J','Ts_Sum(EMA_Ratio,25)',is_quarterly=False,add_data=True)

In [16]:
MassIndex_J.head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20130107,27.914541,25.540692,28.113794,24.368327,24.880011,26.850463,25.752370,NaN,24.367082,25.041144,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.293312
20130108,27.952951,25.029522,28.174451,24.354492,24.857613,26.868521,25.665425,NaN,24.181178,25.206458,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.200069
20130109,27.914236,24.179904,28.059898,24.399803,24.944715,26.573434,25.690375,NaN,24.072958,25.274927,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.167440
20130110,27.742332,23.313172,27.814670,24.434199,24.970629,26.357109,25.555708,NaN,24.031115,25.176447,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.105799

In [17]:
import pandas as pd
print(spearman_factor(factor_u='MassIndex', factor_j='MassIndex_J', start=20130101, symbol=stock_symbol))

(spearmanr    0.865414
dtype: float64, array([0.]))

### OperatingNIToTP

In [18]:
dv.add_field('OperatingNIToTP')

Field name [OperatingNIToTP] not valid, ignore.

False

#### 因无法找到OpearatingNI和TP的数据，无法复现该因子,故选择编写ARTDays

In [19]:
dv.add_field('ARTDays')

Query data - query...
当前请求query...
{'fields': 'ARTDays', 'view': 'factor'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - daily fields prepared.

True

In [20]:
dv.add_formula('ARTDays_J','360/ARTRate',is_quarterly=False,add_data=True)

Variable [ARTRate] is not recognized (it may be wrong),try to fetch from the server...
Query data - query...
当前请求query...
{'fields': 'ARTRate', 'view': 'factor'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - daily fields prepared.

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130107,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130108,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130109,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130110,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130111,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130114,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130115,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130116,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130117,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130118,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130121,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130122,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130123,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130124,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130125,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130128,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130129,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130130,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130131,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130201,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130204,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130205,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130206,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130207,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130208,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130218,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130219,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130220,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
20130221,NaN,-511.872601,-196.046398,43.951214,42.869391,29.495141,33.896390,NaN,2.148487,40.526393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.830701
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20171120,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171121,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171122,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171123,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171124,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171127,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171128,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171129,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171130,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171201,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171204,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171205,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171206,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171207,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171208,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171211,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171212,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171213,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171214,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171215,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171218,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171219,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171220,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171221,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171222,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171225,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171226,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171227,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171228,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098
20171229,NaN,-509.482027,-127.963601,302.648172,93.533217,34.752054,48.727007,NaN,-7.653631,98.535651,...,-36.925349,37.464487,27.753793,10.756158,7.118916,28.604346,-11.112209,82.347828,12.330287,50.920098

In [21]:
print(spearman_factor(factor_u='ARTDays_J', factor_j='ARTDays', start=20130101, symbol=stock_symbol))

(spearmanr    1.0
dtype: float64, array([0.]))

## BBIC

In [22]:
dv.add_field('BBIC')

Query data - query...
当前请求query...
{'fields': 'BBIC', 'view': 'factor'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - daily fields prepared.

True

In [23]:
dv.get_ts('BBIC').head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,0.9598,NaN,0.9557,0.9908,0.9731,0.9683,0.9878,NaN,0.9935,0.9783,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9630
20130107,0.9511,NaN,0.9646,0.9854,0.9689,0.9774,0.9847,NaN,0.9884,0.9799,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9804
20130108,0.9734,NaN,0.9441,0.9737,0.9764,0.9525,0.9843,NaN,0.9736,0.9756,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9611
20130109,0.9855,NaN,0.9650,0.9673,0.9672,0.9624,0.9845,NaN,0.9760,0.9879,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9774
20130110,0.9863,NaN,0.9631,0.9678,0.9727,0.9288,0.9813,NaN,0.9715,0.9911,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9721

In [24]:
dv.add_formula('MA3','Ts_Mean(close_adj,3)',is_quarterly=False,add_data=True)
dv.add_formula('MA6','Ts_Mean(close_adj,6)',is_quarterly=False,add_data=True)
dv.add_formula('MA12','Ts_Mean(close_adj,12)',is_quarterly=False,add_data=True)
dv.add_formula('MA24','Ts_Mean(close_adj,24)',is_quarterly=False,add_data=True)
dv.add_formula('BBI_J','((MA3+MA6+MA12+MA24)/4)',is_quarterly=False,add_data=True)

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,532.807001,1056.129309,246.269655,31.927702,44.971783,149.842848,63.966362,NaN,11.451464,48.533853,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.159488
20130107,538.188415,1059.240886,248.033663,31.962193,45.240281,150.692061,64.174126,NaN,11.466963,48.717524,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.187200
20130108,540.741693,1062.776261,250.668786,32.098575,45.387735,151.877420,64.289713,NaN,11.515422,48.923510,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.230723
20130109,542.600596,1066.055127,252.666906,32.349506,45.720606,153.107993,64.580874,NaN,11.580556,49.056543,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.272359
20130110,543.443250,1068.787515,254.752137,32.570059,45.983052,155.643837,64.782786,NaN,11.655892,49.143229,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.324332
20130111,542.680160,1071.419530,254.409136,32.659293,45.951140,156.662107,64.690609,NaN,11.650791,48.965566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.303507
20130114,550.694416,1073.638898,255.596030,32.809282,46.074385,158.531555,64.882278,NaN,11.695914,48.962133,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.335440
20130115,560.513327,1074.664937,256.396367,32.917186,46.387450,160.715526,65.205629,NaN,11.745746,48.998180,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.412108
20130116,572.780636,1075.534841,256.744813,32.994079,46.833113,162.626255,65.657734,NaN,11.848744,49.074567,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.640408
20130117,580.328359,1076.516270,256.755702,33.264945,46.974514,163.451879,66.099598,NaN,11.886608,49.175844,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.949508
20130118,589.423961,1077.497699,258.546932,33.489928,47.209450,163.634696,66.497568,NaN,11.987252,49.326901,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.198786
20130121,605.582669,1095.286103,262.782729,33.853509,47.467494,163.870588,66.829698,NaN,12.077106,49.580092,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.416019
20130122,623.578580,1123.189918,265.651964,34.238607,47.529667,164.273571,66.809214,NaN,12.119679,49.640172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.518746
20130123,636.543882,1150.067694,269.642759,34.617693,47.523065,164.271605,66.861886,NaN,12.145576,49.633305,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.586028
20130124,642.192920,1172.674023,270.922209,34.785085,47.581386,163.554099,66.544388,NaN,12.087700,49.478816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.495326
20130125,644.200101,1185.376839,272.582772,34.879382,47.637507,162.229170,66.187386,NaN,12.065727,49.379255,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.430309
20130128,657.031591,1204.537013,273.856778,34.979058,47.832278,161.539184,65.877203,NaN,12.040812,49.360373,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.418211
20130129,671.624336,1219.436892,276.660680,35.235685,48.234475,161.965756,65.907929,NaN,12.078676,49.422169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.487076
20130130,684.546240,1241.318302,280.330251,35.599266,49.128001,162.630187,66.090819,NaN,12.182655,49.551769,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.506232
20130131,690.734143,1248.623257,281.468145,35.904939,49.552756,162.665571,66.007421,NaN,12.230917,49.697676,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.652002
20130201,703.970685,1252.593584,282.959930,36.195424,49.808050,163.031204,66.068873,NaN,12.291343,49.907954,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.758098
20130204,715.525536,1252.571279,282.704040,36.265039,49.851516,163.738882,65.972306,NaN,12.318025,50.176595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.855939
20130205,723.250469,1264.025004,284.457159,36.367880,50.020978,164.316818,66.117156,NaN,12.370603,50.352542,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.859836
20130206,725.970108,1270.158936,285.807387,36.561853,50.011624,164.124173,66.131787,NaN,12.406505,50.402322,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.894381
20130207,723.944845,1268.686792,287.418950,36.657732,50.002271,163.601278,66.175681,NaN,12.429655,50.493299,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.935139
20130208,722.574175,1268.987912,288.077730,36.957710,49.946700,162.948642,66.120082,NaN,12.438288,50.572261,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.952727
20130218,720.404250,1264.928365,288.355398,37.539628,50.028130,163.483331,66.301509,NaN,12.496948,50.712160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.940089
20130219,721.543461,1255.827840,287.222949,38.451586,49.824556,164.900652,66.453674,NaN,12.518332,50.656372,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.890694
20130220,719.145694,1246.682704,285.306496,39.141409,49.674351,166.076183,66.617544,NaN,12.519509,50.658088,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.854675
20130221,712.295964,1238.730897,281.849258,39.452778,49.454821,166.144985,66.447822,NaN,12.461634,50.532780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.747672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20171120,1307.494943,3619.516016,596.512060,237.547929,78.024906,213.615672,141.776865,NaN,79.788475,87.942185,...,122.198646,67.647855,42.909180,79.612312,27.607055,60.011275,41.201306,69.160435,48.125292,21.020838
20171121,1334.990287,3691.783051,596.512060,236.900059,77.568352,213.993048,141.423839,NaN,79.421801,87.539467,...,121.450938,65.880616,42.660253,79.634944,27.382947,60.279140,41.456825,67.667980,48.518771,20.852133
20171122,1372.249239,3773.436280,596.512060,236.715347,77.510113,216.511459,142.128389,NaN,79.082200,87.248696,...,120.710417,64.600704,42.522529,79.493306,26.993808,60.384703,41.806624,66.771126,48.757809,20.744040
20171123,1387.473670,3830.259365,596.512060,236.152940,77.127398,217.356064,141.374265,NaN,78.602326,86.798001,...,119.438438,63.430437,42.283188,78.587056,26.574547,59.836109,41.586836,65.813492,48.643062,20.668274
20171124,1403.356799,3864.489016,596.512060,234.796547,76.926681,219.507367,140.511979,NaN,77.866623,86.372022,...,118.093229,62.431465,42.002626,77.455788,26.331772,59.267689,41.497359,65.016701,48.182991,20.870990
20171127,1402.698101,3884.273249,596.512060,232.342910,76.573086,220.128627,138.649202,NaN,77.472089,85.967851,...,117.027917,61.508542,41.496251,76.692476,26.134074,58.951314,41.088409,64.140020,47.711206,20.994573
20171128,1400.392657,3901.314849,596.512060,230.093283,76.490927,221.812702,137.708800,NaN,77.363794,85.799204,...,116.425104,60.859946,41.276935,76.250884,26.151786,59.115512,40.837694,63.659079,47.557415,21.219850
20171129,1396.185487,3960.015172,596.512060,228.441903,76.480528,223.101430,136.344767,NaN,77.661214,85.585487,...,115.546667,60.038776,41.020978,75.824777,26.392545,58.713822,40.564760,63.136202,47.333995,21.433005
20171130,1387.048703,3962.198627,596.512060,227.987015,76.448288,223.599464,135.425396,NaN,77.582739,85.573856,...,114.919583,59.424098,40.639332,75.514753,26.638608,58.766656,40.233576,62.740727,47.282153,21.707109
20171201,1377.104483,3967.377676,596.512060,227.805060,76.370289,223.863884,135.291697,NaN,77.383217,85.543325,...,114.552708,58.865949,40.731255,75.517785,26.858049,58.846488,39.915904,62.619961,47.366532,21.946867
20171204,1369.625070,3938.287132,596.512060,227.736137,75.892936,223.922930,134.928155,NaN,76.936694,85.421202,...,114.065521,58.007234,40.665322,75.236132,26.978853,58.891308,39.780788,62.269872,47.607088,22.030377
20171205,1368.541405,3941.828590,596.512060,227.818844,75.312624,223.042384,134.204075,NaN,76.598859,85.059192,...,113.816875,57.194917,40.700472,74.752741,27.109627,58.845117,39.684406,61.750180,47.747213,21.931377
20171206,1365.736625,3949.097897,596.512060,227.391525,74.804071,222.154137,133.657260,NaN,76.306343,84.732075,...,113.347083,56.571173,40.509809,74.097933,27.227143,58.797766,39.621952,61.332675,47.917923,21.772437
20171207,1355.622418,3916.346072,596.512060,226.266712,74.422396,220.082417,133.163023,NaN,75.926721,84.509635,...,112.757708,56.198718,40.456978,73.563972,27.288553,58.948045,39.468220,60.976216,47.848295,21.523924
20171208,1350.257214,3892.008537,596.512060,225.594029,74.279918,219.340500,133.371835,NaN,75.850011,84.461658,...,112.765729,55.946255,40.484459,73.409231,27.347523,58.899956,39.391655,60.947285,47.909681,21.476444
20171211,1355.824277,3877.922590,596.512060,225.552676,74.305918,218.875839,133.430422,NaN,75.869041,84.579420,...,113.188646,55.731443,40.418952,73.671068,27.485191,58.928851,39.537280,60.934545,48.204899,21.514832
20171212,1353.922552,3863.690191,596.512060,225.299041,74.252879,218.426581,133.096925,NaN,75.845107,84.564881,...,114.081458,55.383414,40.317655,73.925541,27.484978,58.568711,39.576613,61.266320,48.587099,21.635384
20171213,1352.690148,3857.978592,596.512060,224.546409,74.336078,218.660195,133.532574,NaN,75.802926,84.593959,...,114.726563,55.099913,40.303595,74.330424,27.493782,58.360747,40.027900,61.668165,49.308116,21.708793
20171214,1347.356817,3858.138357,596.512060,223.487761,74.010562,218.424014,134.289703,NaN,75.727983,84.548889,...,115.458854,54.674449,40.374535,74.733683,27.369902,58.664783,40.455466,61.810430,49.826537,21.756947
20171215,1341.811002,3838.953244,596.512060,223.280994,73.758886,216.547400,135.568109,NaN,75.449593,84.695728,...,116.174688,54.392015,40.397755,75.171810,27.353144,59.065103,40.796859,61.699219,50.159714,21.700375
20171218,1335.585240,3808.544639,596.512060,223.338888,73.466650,214.049527,136.138960,NaN,75.299705,84.646297,...,116.647396,54.110861,40.349716,75.459310,27.329280,59.725167,40.865318,61.700016,50.403958,21.615180
20171219,1338.028798,3791.103626,596.512060,223.482247,73.237853,211.821208,136.543062,NaN,75.221230,84.607043,...,117.256458,53.871197,40.231271,75.762945,27.456554,60.176001,40.997731,61.927215,50.507425,21.486883
20171220,1343.723352,3774.062026,596.512060,223.904052,72.887378,209.813667,136.936649,NaN,74.910665,84.512543,...,117.863854,53.509195,40.174072,76.041566,27.504706,60.598995,41.125941,61.954022,50.572282,21.331310
20171221,1353.072618,3783.914201,596.512060,224.061195,72.571222,208.696941,137.919114,NaN,74.659938,84.537258,...,118.623021,53.234227,40.149041,76.426308,27.559434,60.928763,41.352635,61.897753,50.866849,21.280126
20171222,1357.481648,3788.693837,596.512060,224.179742,72.499463,207.767619,138.252611,NaN,74.366834,84.746613,...,118.828333,53.097383,40.102387,76.606605,27.498660,60.980754,41.577828,61.593582,50.964893,21.189881
20171225,1359.266507,3813.484040,596.512060,224.408564,72.404825,206.971791,137.925123,NaN,73.928158,84.739344,...,119.276042,52.969179,40.055201,76.850683,27.300007,61.148327,41.636979,61.210847,50.990706,21.190217
20171226,1363.834899,3831.803760,596.512060,225.519593,72.381945,206.530234,137.666738,NaN,73.675273,84.764059,...,119.295208,52.979098,40.039436,76.947058,27.130309,61.588721,41.811729,61.044960,50.877478,21.141727
20171227,1360.350172,3852.107229,596.512060,226.247413,72.258187,205.675361,136.738354,NaN,73.408458,84.604136,...,119.089896,52.771006,39.973290,76.845810,27.002505,61.783292,41.812930,60.637540,50.699392,21.167656
20171228,1358.767172,3868.350004,596.512060,226.889770,72.193708,205.346761,136.879564,NaN,73.328217,84.554704,...,118.555000,52.691224,39.967112,76.766869,27.186734,61.857324,41.983176,60.568531,50.585947,21.423913
20171229,1354.379391,3883.820581,596.512060,227.576237,72.218667,205.713869,137.199541,NaN,73.212859,84.550343,...,118.369375,52.532409,39.930577,76.945217,27.305735,62.017620,42.236593,60.444315,50.613929,21.618211

In [26]:
BBIC_J=dv.add_formula('BBIC_J','BBI_J/close_adj',is_quarterly=False,add_data=True)

In [27]:
BBIC_J.head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,0.959747,0.974741,0.955734,0.990604,0.973060,0.968318,0.987866,NaN,0.993498,0.980103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.963035
20130107,0.951003,0.977612,0.964537,0.985175,0.968903,0.977382,0.984667,NaN,0.988383,0.982177,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.980344
20130108,0.973431,0.980875,0.944082,0.973877,0.976480,0.952429,0.984319,NaN,0.973593,0.978206,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.961120
20130109,0.985400,0.983902,0.964904,0.967227,0.967155,0.962423,0.984542,NaN,0.975992,0.990658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.977523
20130110,0.986308,0.986423,0.963253,0.967669,0.972707,0.928784,0.981316,NaN,0.971546,0.994063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.972051

In [28]:
print(spearman_factor(factor_u='BBIC', factor_j='BBIC_J', start=20130101, symbol=stock_symbol))

(spearmanr    0.99194
dtype: float64, array([0.]))

### GrossIncomeRatio

In [29]:
dv.add_field('GrossIncomeRatio')

Query data - query...
当前请求query...
{'fields': 'GrossIncomeRatio', 'view': 'factor'}
下载进度398/1219.
下载进度796/1219.
下载进度1194/1219.
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - daily fields prepared.

True

In [30]:
GrossIncomeRatio_U=dv.get_ts('GrossIncomeRatio')

In [31]:
GrossIncomeRatio_U.head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,0.4334,0.3785,0.4518,0.3181,0.3485,0.2291,0.022,NaN,0.1567,0.1481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3242
20130107,0.4334,0.3785,0.4518,0.3181,0.3485,0.2291,0.022,NaN,0.1567,0.1481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3242
20130108,0.4334,0.3785,0.4518,0.3181,0.3485,0.2291,0.022,NaN,0.1567,0.1481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3242
20130109,0.4334,0.3785,0.4518,0.3181,0.3485,0.2291,0.022,NaN,0.1567,0.1481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3242
20130110,0.4334,0.3785,0.4518,0.3181,0.3485,0.2291,0.022,NaN,0.1567,0.1481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3242

In [32]:
dv.add_field('total_oper_rev')

Query data - query...
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - quarterly fields prepared.
Query data - query...
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - quarterly fields prepared.

True

In [33]:
dv.get_ts('total_oper_rev').head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,2.953167e+10,4.612822e+10,2.027707e+09,5606719.63,2.923503e+09,5.293060e+09,1.238028e+10,NaN,3.044915e+08,1.004276e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.435651e+09
20130107,2.953167e+10,4.612822e+10,2.027707e+09,5606719.63,2.923503e+09,5.293060e+09,1.238028e+10,NaN,3.044915e+08,1.004276e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.435651e+09
20130108,2.953167e+10,4.612822e+10,2.027707e+09,5606719.63,2.923503e+09,5.293060e+09,1.238028e+10,NaN,3.044915e+08,1.004276e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.435651e+09
20130109,2.953167e+10,4.612822e+10,2.027707e+09,5606719.63,2.923503e+09,5.293060e+09,1.238028e+10,NaN,3.044915e+08,1.004276e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.435651e+09
20130110,2.953167e+10,4.612822e+10,2.027707e+09,5606719.63,2.923503e+09,5.293060e+09,1.238028e+10,NaN,3.044915e+08,1.004276e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.435651e+09

In [34]:
dv.add_field('oper_exp')

Query data - query...
WARNING: some data is unavailable:
    At fields 000024.SZ, 000522.SZ, 000527.SZ, 000562.SZ, 000748.SZ, 600005.SH, 600832.SH, 601268.SH, 601299.SH
Query data - quarterly fields prepared.

True

In [35]:
dv.get_ts('oper_exp').head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,1.617159e+10,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
20130107,1.617159e+10,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
20130108,1.617159e+10,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
20130109,1.617159e+10,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
20130110,1.617159e+10,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

#### 营业成本数据异常，该因子无法复现

In [36]:
dv.add_formula('GrossIncomeRatio_J','((total_oper_rev)-(total_oper_rev))/(oper_exp)',is_quarterly=False,add_data=True)
GrossIncomeRatio_J=dv.get_ts('GrossIncomeRatio_J')

### alpha59

In [37]:
alpha59=dv.add_formula('alpha59',
                       'Ts_Sum(If(close_adj==Delay(close_adj,1),0,close_adj-If(close_adj>Delay(close_adj,1),Min(low_adj,Delay(close_adj,1)),Max(high_adj,Delay(close_adj,1)))),20)',
                       is_quarterly=False,add_data=True)

In [38]:
alpha59.head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,131.237064,132.76060,60.629604,5.741347,3.697351,30.571668,7.02300,NaN,1.883400,6.179595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.634866
20130107,119.432672,109.20630,48.608217,6.379275,2.218411,21.135968,5.19702,NaN,1.732728,5.108465,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.113539
20130108,99.642956,93.14655,52.789569,6.379275,2.271230,29.628098,8.42760,NaN,2.128242,5.190860,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.557521
20130109,75.339796,114.55955,42.336189,6.045123,2.112772,20.758540,7.16346,NaN,1.808064,3.707757,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.026415
20130110,62.493840,95.28785,48.608217,6.045123,1.214844,25.287676,6.03978,NaN,1.864566,2.554233,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.958406

### alpha112

In [39]:
alpha112=dv.add_formula('alpha112','((Ts_Sum(If((close_adj-Delay(close_adj,1))>0,(close_adj-Delay(close_adj,1)),0),12)-Ts_Sum(If((close_adj-Delay(close_adj,1))<0,Abs(close_adj-Delay(close_adj,1)),0),12))/(Ts_Sum(If((close_adj-Delay(close_adj,1))>0,(close_adj-Delay(close_adj,1)),0),12)+Ts_Sum(If((close_adj-Delay(close_adj,1))<0,Abs(close_adj-Delay(close_adj,1)),0),12))*100)',
                        is_quarterly=False,
                        add_data=True)

In [40]:
alpha112.head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,47.368421,28.378378,44.186047,7.692308,26.400000,51.063830,25.423729,NaN,21.839080,51.219512,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.164010
20130107,54.545455,40.740741,42.635659,2.941176,30.303030,47.916667,31.147541,NaN,24.444444,52.380952,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.608538
20130108,33.333333,90.000000,60.000000,22.535211,29.323308,56.140351,30.000000,NaN,41.666667,57.446809,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.749345
20130109,29.310345,89.010989,31.313131,47.142857,32.857143,53.448276,31.147541,NaN,31.707317,39.622642,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.266017
20130110,33.628319,86.486486,34.615385,48.251748,46.456693,65.605096,28.813559,NaN,34.883721,37.037037,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.749957

### alpha134

In [41]:
alpha134=dv.add_formula('alpha134','(((close_adj-Delay(close_adj,12))/Delay(close_adj,12))*volume)',is_quarterly=False,add_data=True)

In [42]:
alpha134.head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,2.368377e+06,0.0,3.434525e+06,3651.130476,6.204623e+05,1.290668e+06,378536.098655,NaN,22502.888702,222569.296552,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.973031e+06
20130107,2.534447e+06,0.0,1.665295e+06,890.263158,6.169953e+05,8.024209e+05,250228.719101,NaN,25650.037037,166914.265517,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.490379e+05
20130108,1.536783e+06,0.0,8.953778e+06,8393.876543,9.001686e+05,3.334481e+06,313641.946309,NaN,106311.564626,418360.810345,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.943628e+06
20130109,1.125849e+06,0.0,1.438132e+06,40893.982609,1.354818e+06,1.247501e+06,358443.906250,NaN,84984.615894,220070.187931,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.534947e+06
20130110,1.207300e+06,0.0,1.771590e+06,33176.382098,1.335212e+06,4.503288e+06,300190.953642,NaN,66233.080725,254362.034483,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.023363e+05

### alpha191

In [43]:
alpha191=dv.add_formula('alpha191','((Correlation(Ts_Mean(volume,20),low_adj,5)+(high_adj+low_adj)/2)-close_adj)',is_quarterly=False,add_data=True)

In [44]:
alpha191.head()

symbol,000001.SZ,000002.SZ,000006.SZ,000008.SZ,000009.SZ,000012.SZ,000021.SZ,000024.SZ,000025.SZ,000027.SZ,...,603833.SH,603858.SH,603866.SH,603868.SH,603877.SH,603883.SH,603885.SH,603888.SH,603899.SH,603993.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
20130104,7.764099,-1083.4978,4.491852,1.021581,1.239200,2.645249,1.567294,NaN,0.236735,0.548913,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.671199
20130107,-5.425566,-1083.4978,-1.167517,-0.269237,0.716223,1.034781,0.405158,NaN,0.139064,0.686544,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.706817
20130108,4.988114,-1083.4978,4.888209,-0.074348,0.564638,-0.186752,0.301096,NaN,-0.144849,0.634700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.564617
20130109,2.630409,-1083.4978,0.918322,0.319651,0.262544,0.719571,0.210257,NaN,1.067226,0.445727,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.365227
20130110,3.522058,-1083.4978,0.616228,0.856023,0.612504,-2.485728,-0.517909,NaN,0.803202,-0.740964,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.182957